// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type OneTimeCode struct {
	ID        uuid.UUID
	Code      int32
	ExpiresAt time.Time
	UserID    uuid.UUID
}

type User struct {
	ID        uuid.UUID
	ApiKey    string
	FirstName string
	LastName  string
	Email     string
	CreatedAt time.Time
	UpdatedAt time.Time
}
