version: "3.8"
services:
  swiftlio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6969:6969" # Or use whatever port you decide to use here
      - "7331:7331" # Or use whatever proxy you change in the templ generate cmd
    volumes:
      - .:/app
    command: make dev
